// <auto-generated />
using System;
using LeaveManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeaveManagementSystem.Migrations
{
    [DbContext(typeof(LeaveManagementDbContext))]
    [Migration("20250820215415_InitialCreate1")]
    partial class InitialCreate1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeaveManagementSystem.Models.CompanyHoliday", b =>
                {
                    b.Property<int>("HolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("holiday_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HolidayId"));

                    b.Property<bool>("CompensatedIfOnWeekend")
                        .HasColumnType("bit")
                        .HasColumnName("compensated_if_on_weekend");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("holiday_date");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("holiday_name");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit")
                        .HasColumnName("is_recurring");

                    b.Property<bool>("IsWeekend")
                        .HasColumnType("bit")
                        .HasColumnName("is_weekend");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("HolidayId");

                    b.ToTable("company_holidays");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.CompanyWeekendPolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("day_of_week");

                    b.Property<bool>("IsHoliday")
                        .HasColumnType("bit")
                        .HasColumnName("is_holiday");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int")
                        .HasColumnName("office_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("PolicyId");

                    b.ToTable("company_weekend_policy");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DepartmentHeadId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("department_head_id");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("department_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("TotalEmployees")
                        .HasColumnType("int")
                        .HasColumnName("total_employees");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("DepartmentId");

                    b.HasIndex("DepartmentHeadId");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("employee_name");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("employment_status");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("hire_date");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("job_title");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("manager_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("employees");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.LeaveApproval", b =>
                {
                    b.Property<Guid>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approval_id");

                    b.Property<int>("ApprovalLevel")
                        .HasColumnType("int")
                        .HasColumnName("approval_level");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("approved_at");

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approver_id");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RequestGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("request_group_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("ApprovalId");

                    b.HasIndex("ApproverId");

                    b.HasIndex("RequestGroupId");

                    b.ToTable("leave_approvals");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.LeaveBalance", b =>
                {
                    b.Property<Guid>("BalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("balance_id");

                    b.Property<decimal>("AllocatedDays")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("allocated_days");

                    b.Property<decimal>("CarriedForwardDays")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("carried_forward_days");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int")
                        .HasColumnName("leave_type_id");

                    b.Property<decimal>("PendingDays")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("pending_days");

                    b.Property<decimal>("RemainingDays")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("remaining_days");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("UsedDays")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("used_days");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("BalanceId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("EmployeeId", "LeaveTypeId", "Year")
                        .IsUnique();

                    b.ToTable("leave_balances");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.LeaveBalanceHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("history_id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("action_type");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("balance_after");

                    b.Property<decimal>("BalanceBefore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("balance_before");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("changed_by");

                    b.Property<decimal>("DaysChanged")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("days_changed");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int")
                        .HasColumnName("leave_type_id");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.HasKey("HistoryId");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("leave_balance_history");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.LeaveRequest", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("request_id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("Approver1Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approver1_id");

                    b.Property<Guid?>("Approver2Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approver2_id");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("HalfDayType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("half_day_type");

                    b.Property<bool>("IsHalfDay")
                        .HasColumnType("bit")
                        .HasColumnName("is_half_day");

                    b.Property<DateTime>("LeaveDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("leave_date");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int")
                        .HasColumnName("leave_type_id");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rejection_reason");

                    b.Property<Guid>("RequestGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("request_group_id");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("requested_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("RequestId");

                    b.HasIndex("Approver1Id");

                    b.HasIndex("Approver2Id");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("RequestGroupId");

                    b.ToTable("leave_requests");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.LeaveRequestGroup", b =>
                {
                    b.Property<Guid>("RequestGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("request_group_id");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<Guid?>("FinalApproverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("final_approver_id");

                    b.Property<bool>("IsResponded")
                        .HasColumnType("bit")
                        .HasColumnName("is_responded");

                    b.Property<string>("OverallStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("overall_status");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("requested_at");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("responded_at");

                    b.Property<decimal>("TotalDays")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("total_days");

                    b.Property<int>("TotalRequests")
                        .HasColumnType("int")
                        .HasColumnName("total_requests");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("RequestGroupId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FinalApproverId");

                    b.ToTable("leave_request_groups");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.LeaveType", b =>
                {
                    b.Property<int>("LeaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("leave_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsPaidLeave")
                        .HasColumnType("bit")
                        .HasColumnName("is_paid_leave");

                    b.Property<string>("LeaveTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("leave_type_name");

                    b.Property<int>("MaxDaysPerYear")
                        .HasColumnType("int")
                        .HasColumnName("max_days_per_year");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("LeaveTypeId");

                    b.ToTable("leave_types");

                    b.HasData(
                        new
                        {
                            LeaveTypeId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yearly vacation leave",
                            IsPaidLeave = true,
                            LeaveTypeName = "Annual Leave",
                            MaxDaysPerYear = 21,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            LeaveTypeId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Medical leave",
                            IsPaidLeave = true,
                            LeaveTypeName = "Sick Leave",
                            MaxDaysPerYear = 10,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            LeaveTypeId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Maternity leave",
                            IsPaidLeave = true,
                            LeaveTypeName = "Maternity Leave",
                            MaxDaysPerYear = 90,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            LeaveTypeId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Personal time off",
                            IsPaidLeave = false,
                            LeaveTypeName = "Personal Leave",
                            MaxDaysPerYear = 5,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("notification_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("notification_type");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("read_at");

                    b.Property<Guid?>("RelatedRequestGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("related_request_group_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("NotificationId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RelatedRequestGroupId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.SpecialLeave", b =>
                {
                    b.Property<int>("SpecialLeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("special_leave_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecialLeaveId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit")
                        .HasColumnName("is_mandatory");

                    b.Property<bool>("IsWeekend")
                        .HasColumnType("bit")
                        .HasColumnName("is_weekend");

                    b.Property<DateTime>("SpecialDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("special_date");

                    b.HasKey("SpecialLeaveId");

                    b.ToTable("special_leaves");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int")
                        .HasColumnName("user_role_id");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserRoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.ToTable("user_roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Employee"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "HR_Admin"
                        },
                        new
                        {
                            RoleId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Super_Admin"
                        });
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.Department", b =>
                {
                    b.HasOne("LeaveManagementSystem.Models.Employee", "DepartmentHead")
                        .WithMany()
                        .HasForeignKey("DepartmentHeadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DepartmentHead");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.Employee", b =>
                {
                    b.HasOne("LeaveManagementSystem.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeaveManagementSystem.Models.Employee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeaveManagementSystem.Models.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("LeaveManagementSystem.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Manager");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.LeaveApproval", b =>
                {
                    b.HasOne("LeaveManagementSystem.Models.Employee", "Approver")
                        .WithMany("LeaveApprovals")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeaveManagementSystem.Models.LeaveRequestGroup", "RequestGroup")
                        .WithMany("LeaveApprovals")
                        .HasForeignKey("RequestGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("RequestGroup");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.LeaveBalance", b =>
                {
                    b.HasOne("LeaveManagementSystem.Models.Employee", "Employee")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeaveManagementSystem.Models.LeaveType", "LeaveType")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.LeaveBalanceHistory", b =>
                {
                    b.HasOne("LeaveManagementSystem.Models.Employee", "ChangedByEmployee")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeaveManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeaveManagementSystem.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByEmployee");

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.LeaveRequest", b =>
                {
                    b.HasOne("LeaveManagementSystem.Models.Employee", "Approver1")
                        .WithMany()
                        .HasForeignKey("Approver1Id");

                    b.HasOne("LeaveManagementSystem.Models.Employee", "Approver2")
                        .WithMany()
                        .HasForeignKey("Approver2Id");

                    b.HasOne("LeaveManagementSystem.Models.LeaveType", "LeaveType")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeaveManagementSystem.Models.LeaveRequestGroup", "RequestGroup")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("RequestGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver1");

                    b.Navigation("Approver2");

                    b.Navigation("LeaveType");

                    b.Navigation("RequestGroup");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.LeaveRequestGroup", b =>
                {
                    b.HasOne("LeaveManagementSystem.Models.Employee", "Employee")
                        .WithMany("LeaveRequestGroups")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeaveManagementSystem.Models.Employee", "FinalApprover")
                        .WithMany()
                        .HasForeignKey("FinalApproverId");

                    b.Navigation("Employee");

                    b.Navigation("FinalApprover");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.Notification", b =>
                {
                    b.HasOne("LeaveManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeaveManagementSystem.Models.LeaveRequestGroup", "RelatedRequestGroup")
                        .WithMany()
                        .HasForeignKey("RelatedRequestGroupId");

                    b.Navigation("Employee");

                    b.Navigation("RelatedRequestGroup");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.User", b =>
                {
                    b.HasOne("LeaveManagementSystem.Models.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.Employee", b =>
                {
                    b.Navigation("LeaveApprovals");

                    b.Navigation("LeaveBalances");

                    b.Navigation("LeaveRequestGroups");

                    b.Navigation("Subordinates");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.LeaveRequestGroup", b =>
                {
                    b.Navigation("LeaveApprovals");

                    b.Navigation("LeaveRequests");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.LeaveType", b =>
                {
                    b.Navigation("LeaveBalances");

                    b.Navigation("LeaveRequests");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.User", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LeaveManagementSystem.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
